### ISSUE TITLE
For some reason, there are two 'Safe Exam Browser access rule' titles in capabilities management

### ISSUE THREAD

**Issue by lucaboesch** [catalyst/moodle-quizaccess_seb#210]
There are two 'Safe Exam Browser access rule' titles in capabilities management.

To reproduce, go to admin/roles/define.php and edit a role's capabilities.
Do filter the capabilities for "seb".

<img width="826" alt="grafik" src="https://user-images.githubusercontent.com/377279/76185034-5e365e00-61ce-11ea-867c-c739eacc7c6b.png">

**Comment by lucaboesch** [comment]
Note: it is probably related to the capability being named differently seb:manage_filemanager_sebconfigfile, that should probably be seb:manage_seb_filemanager_configfile to sort along with the others correctly.

**Comment by dmitriim** [comment]
@lucaboesch it happens because of the different context of these capabilities. Templates management is in the System context hence it's displayed in the different section to where the rest of caps are displayed as they are in lower context (course module).

I recon we can close this off as it's how Moodle works.
