### ISSUE TITLE
Lock down quiz SEB settings if there is at least one active quiz attempt

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#35]

**Comment by 1JackBlack1** [comment]
Rather than create a new issue I thought it best to comment here.
I understand not wanting to change settings while a student is currently attempting a quiz which would result in them being locked out. But I don't see why the settings need to be locked once the student has completed that attempt.

This can cause issues with URL filtering if a key part of the Moodle site changes, such moving to a different domain or an alternate login process, and also causes issues with any updates to SEB if you are using browser exam keys.

So was this intended to just restrict changing while there are active (i.e. in progress) quiz attempts, or was it intended to restrict changing as long as there is any attempt.

If the former then there is a bug as it doesn't only restrict then. If the latter, could I ask what the justification for that is?

**Comment by Aaron-Rumpler** [comment]
@dmitriim Same question as above. Is there a technical reason for locking the SEB settings when the are (completed) quiz attempts?
