### ISSUE TITLE
Install script to save default SEB settings for existing quizzes.

### ISSUE THREAD

**Issue by andrewmadden** [catalyst/moodle-quizaccess_seb#43]

**Comment by dmitriim** [comment]
If not done then error:

No SEB config could be found for quiz with cmid: 4

More information about this error

×Debug info: 
Error code: noconfigfound
×Stack trace:
line 64 of /mod/quiz/accessrule/seb/classes/access_manager.php: moodle_exception thrown
line 67 of /mod/quiz/accessrule/seb/rule.php: call to quizaccess_seb\access_manager->__construct()
line 71 of /mod/quiz/accessmanager.php: call to quizaccess_seb::make()
line 56 of /mod/quiz/accessmanager.php: call to quiz_access_manager->make_rules()
line 69 of /mod/quiz/view.php: call to quiz_access_manager->__construct()

**Comment by dmitriim** [comment]
Maybe it's a better idea to create a new default set of settings if not found on the fly in access_manager, otherwise could be really time consuming on the big sites to go through all quizzes.  

From another hand if we never touch the quiz after the plugin is installed and then will need to back it up, then this will could be somehow managed.
