### ISSUE TITLE
Fix privacy provider 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-quizaccess_seb#48]
Fix privacy provided issue:

There was 1 failure:

1) provider_testcase::test_table_coverage
The following tables with user fields must be covered with metadata providers: 
  - quizaccess_seb_quizsettings (usermodified)

/var/www/site/privacy/tests/provider_test.php:327
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

**Comment by andrewmadden** [comment]
@nhoobin  So I'm a bit stuck on this one. 

The issue is that the `quizsettings` table is a persistent object and therefore keeps track of the last user to modify the settings.

Because we keep track of the user, we need to provide a non-null privacy provider. All of the privacy providers I've found are quite complicated (500+ lines of code).

1. Do we need to implement a full provider?
2. Does every column in the database need to be provided as metadata?
3. In the case of the `delete_data_for_user` method, do all SEB settings for a quiz need to be deleted? Or just the reference to who modified the settings?

Examples:
* mod/assignment/classes/privacy
* mod/workshop/classes/privacy
